# Change these first
owner: electrotempo # Your GitHub organization or username, where this repository lives
repo: electrotempo-status # The name of this repository

sites:
  - name: ElectoTempo Frontend
    url: $ET_FRONTEND_HEALTH_ENDPOINT
  - name: ElectoTempo Backend
    url: $ET_BACKEND_HEALTH_ENDPOINT

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /electrotempo-status
  logoUrl: "https://media.licdn.com/dms/image/C4E0BAQG4nepOjpHIkA/company-logo_200_200/0/1643996190715/electrotempo_logo?e=2147483647&v=beta&t=yjqCLGM9xAvVmqzk1RZfNeqRxKwfSqmZmzMbaGvhJ80"
  name: ElectroTempo Status
  introTitle: "Welcome to ElectroTempo status page!"
  introMessage: "**Real-time** status from our [ElectroTempo Platform]($ET_PLATFORM_URL)."
  navbar:
    - title: Status
      href: /
    - title: Login
      href: $ET_PLATFORM_URL
    - title: About
      href: $ET_WEBSITE_URL

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
